---
- name: install flatpak
  community.general.xbps:
    name: flatpak

- name: Add the flathub flatpak repo
  community.general.flatpak_remote:
    name: "{{ item.name }}"
    state: present
    flatpakrepo_url: "{{ item.repo }}"
  loop:
    - { name: 'flathub', repo: 'https://dl.flathub.org/repo/flathub.flatpakrepo' }

- name: Install flatpak packages
  community.general.flatpak:
    name: '{{ item }}'
    state: present
    remote: flathub
  loop:
    - com.spotify.Client
    - com.vscodium.codium
